### ISSUE TITLE
Unable to start Sauce Connect after upgrading to version 1.159

### ISSUE THREAD

**Issue by poonamsl** [saucelabs/ci-sauce#131]
**Short summary of what the user sees:**
User is seeing the following error in Sauce Connect logs:
`2022-08-09 15:56:42.220 [17084] [CLI] [fatal] extra info is not valid JSON.`
 
**Exact steps to reproduce the problem:**
Code used for connection
```
if (bSauceLabsExecution) {
    final String testUser = Suite.config.getProperty("sauceLabs.username");
    final String testKey = Suite.config.getProperty("sauceLabs.key");

    tunnelOptions =
            "--tunnel-identifier=" + tunnelId + " --readyfile=connectSet.txt --no-remove-colliding-tunnels";
    /*tunnelOptions =
                "--tunnel-name=" + tunnelId + " --readyfile=connectSet.txt --no-remove-colliding-tunnels";*/

    manager = new SauceConnectFourManager();

    Suite.manager = manager;
    try {
        tunnel = manager.openConnection(testUser,
                testKey, 0, null, tunnelOptions,
                null, false, null);
    } catch (AbstractSauceTunnelManager.SauceConnectException e) {
        e.printStackTrace();
    }
```
 
**Isolation: What must be true for it to happen? When does it not happen?**
User has been using version 1.154.
(Unable to use version 1.158 due to tunnel_name issue.)
 
**Links to Relevant Test Archives or Logs:**
Console output:
`INFO: Launching Sauce Connect 4.8.0 [C:\Users\MO001\sc-4.8.0-win32\bin\sc.exe, -u, ****, -k, ****, -P, 0, --tunnel-identifier=****, --readyfile=connectSet.txt, --no-remove-colliding-tunnels, -v, -l=mySaucelog.txt, --extra-info, {"runner": "jenkins"}]`
 
**What attempts were made to find the root cause so far?**
NA

**Comment by aaronmray** [comment]
I ran into this issue yesterday via the Jenkins Sauce OnDemand plugin. I cut a PR that addresses the problem. Fixing the plugin in the interim requires compiling this library with the fix, and then recompiling the plugin referencing the fixed version of ci-sauce.

**Comment by alexh-sauce** [comment]
@aaronmray Did the latest 1.209 version fix the issue for you? I've had reports from other customers that it's still broken, but I haven't been able to reproduce.

**Comment by psiservices-aray** [comment]
@alexh-sauce I confirmed today that 1.209 is working.

**Comment by alexh-sauce** [comment]
Thank you!
