### ISSUE TITLE
Add support of SauceConnect 5

### ISSUE THREAD

**Issue by valfirst** [saucelabs/ci-sauce#254]
Please implement support of SauceConnect 5: https://docs.saucelabs.com/secure-connections/sauce-connect-5/

**Comment by valfirst** [comment]
@alexh-sauce thank you for the implementation! when is new release planned to be published?

**Comment by alexh-sauce** [comment]
We're working on it now - first we need to implement a version check like we had in SC 4. Once that's done, we'll release a new version.
