### ISSUE TITLE
Update to latest sauce connect

### ISSUE THREAD

**Issue by bootstraponline** [saucelabs/ci-sauce#26]
I see `CURRENT_SC_VERSION = "4.4.6";` It looks like[ 4.4.8 is released. ](https://wiki.saucelabs.com/display/DOCS/Sauce+Connect+Proxy)

**Comment by valfirst** [comment]
@bootstraponline, master branch is already [updated to sauce connect 4.4.9](https://github.com/saucelabs/ci-sauce/commit/a7f3187442f043b5e90057c75338c507da074644). `ci-sauce:1.129` is released.

**Comment by bootstraponline** [comment]
Thanks.
