### ISSUE TITLE
Javascript alert on job miscellaneous tab: "blockUI requires jQuery v1.2.3 or later!  You are using v1.10.2"

### ISSUE THREAD

**Issue by konrness** [saucelabs/ci-sauce#8]
The Bamboo plugin is reporting a Javascript error on the job miscellaneous tab. It seems to be caused by a incorrect comparison of the semantic versioning by blockUI jQuery plugin.

The errors are coming from https://myhost/s/d41d8cd98f00b204e9800998ecf8427e-CDN/en_US/4410/1/1.6.48/_/download/batch/com.saucelabs.bamboo.bamboo-sauceondemand-plugin:sodJS/com.saucelabs.bamboo.bamboo-sauceondemand-plugin:sodJS.js

We see this error message on https://myhost/build/admin/edit/editMiscellaneous.action?buildKey=ABC-ABC-JOB1

The error message is: "blockUI requires jQuery v1.2.3 or later!  You are using v1.10.2"

The plugin is using the jQuery BlockUI Plugin version 2.33. The latest version of this plugin does not check for jQuery version.

Bamboo Sauce OnDemand Plugin Version: 1.6.49
Workaround: Click the OK button. It seems all the UI functionality still works.

**Comment by colinpade** [comment]
hi @halkeye :)

**Comment by halkeye** [comment]
hi @colinpade
